### ISSUE TITLE
Unreachable: "unexpected cargo crate type: test"

### ISSUE THREAD

**Issue by djc** [cognitive-engineering-lab/argus#43]
# Problem

While working in https://github.com/open-telemetry/opentelemetry-rust (specifically in `/opentelemetry-proto/tests/grpc_build.rs`), this broke Argus.

# Logs

**OS:** darwin (24.0.0)
**VSCode:** 1.93.1
**Error message**
```
thread 'main' panicked at /Users/djc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc_plugin-0.10.0-nightly-2024-05-20/src/cli.rs:184:10:
internal error: entered unreachable code: unexpected cargo crate type: test
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rustc_plugin::cli::only_run_on_file
   3: rustc_plugin::cli::cli_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Full log:** https://paste.rs/OT4li

**Comment by djc** [comment]
Similarly,

```
thread 'main' panicked at /Users/djc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc_plugin-0.10.0-nightly-2024-05-20/src/cli.rs:184:10:
internal error: entered unreachable code: unexpected cargo crate type: bench
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rustc_plugin::cli::only_run_on_file
   3: rustc_plugin::cli::cli_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
