### ISSUE TITLE
Argus crashes when error is in a proc macro

### ISSUE THREAD

**Issue by willcrichton** [cognitive-engineering-lab/argus#9]
# Problem

Click on the compile error at `shell.rs:88`:

[files.tar.gz](https://github.com/cognitive-engineering-lab/argus/files/15395024/files.tar.gz)

# Logs

**OS:** darwin (23.2.0)
**VSCode:** 1.89.1
**Error message**
```
[INFO src/plugin.rs:235] - Starting rustc analysis...
[INFO src/timer.rs:8] - rustc took 0.0906s
[INFO src/timer.rs:8] - global_ctxt took 0.0000s
thread 'rustc' panicked at /Users/will/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc_utils-0.9.0-nightly-2024-01-24/src/source_map/range.rs:92:26:
Could not find byte pos for CharPos { line: 10, column: 43 }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: rustc_utils::source_map::range::CharByteMapping::char_to_byte
   3: rustc_utils::source_map::range::ByteRange::from_char_range
   4: <rustc_utils::source_map::range::CharRange as rustc_utils::source_map::range::ToSpan>::to_span
   5: rustc_middle::ty::context::GlobalCtxt::enter
   6: <argus_cli::plugin::ArgusCallbacks<A,T,F> as rustc_driver_impl::Callbacks>::after_expansion
   7: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#0}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
   8: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
   9: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  10: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: could not compile `rust-tutor` (bin "rust-tutor")

```

**Full log:** https://paste.rs/YgzR4

**Comment by gavinleroy** [comment]
![Screen Shot 2024-06-11 at 15 25 06](https://github.com/cognitive-engineering-lab/argus/assets/20209337/fce685de-b0b2-40fb-9fef-bfd81437febf)

Not anymore :)
